name: edubazaar
description: "Student Marketplace & Learning Community - EduBazaar Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  shared_preferences: ^2.3.3
  provider: ^6.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  # Image handling packages
  image: ^4.1.3
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  photo_view: ^0.14.0
  file_picker: ^8.0.0+1
  # Authentication dependencies
  supabase_flutter: ^2.8.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.5
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/edu2.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/edu2.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/edu2.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/edu2.png"
